import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LayoutWrapper } from "@/components/layout/LayoutWrapper";
import NavigationBar from "@/components/navigation";
import NavigationFooter from "@/components/navigation/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI SaaS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutWrapper>
        <NavigationBar/>
        {children}
        <NavigationFooter/>
        </LayoutWrapper>
      </body>
    </html>
  );
}
